### ISSUE TITLE
Failure when log_level is a symbol

### ISSUE THREAD

**Issue by mkamensky** [graphiti-api/graphiti-rails#46]
https://github.com/graphiti-api/graphiti-rails/blob/d4a7bcf5ae39c21c7baa768d60e83bc3f2f70617/lib/graphiti/rails/railtie.rb#L40

The level could be a symbol here, which does not respond to `zero?`. I suggest replacing it with `blank?`

**Comment by wagenet** [comment]
@mkamensky can you make a PR?
